const fs = require('fs');
const path = require('path');

const root = process.cwd();

function applyReplacements(relativePath, replacements) {
  const filePath = path.join(root, relativePath);
  let content = fs.readFileSync(filePath, 'utf8');
  for (const [from, to] of replacements) {
    content = content.split(from).join(to);
  }
  fs.writeFileSync(filePath, content, 'utf8');
}

const replacementsByFile = {
  'app/page.tsx': [
    ["Contribuer a eliminer l'extreme pauvrete et la faim.", "Contribuer à éliminer l'extrême pauvreté et la faim."],
    ["Annee de creation", "Année de création"],
    ["Le collectif est fonde le 17 avril 2020.", "Le collectif est fondé le 17 avril 2020."],
    ["Axe structurants", "Axes structurants"],
    ["Contribuer a l'amelioration de la sante des populations.", "Contribuer à l'amélioration de la santé des populations."],
    ["Promouvoir des mÃ©canismes d'inclusion pour les publics vulnÃ©rables.", "Promouvoir des mécanismes d'inclusion pour les publics vulnérables."],
    ["Developper la resilience face au rechauffement climatique.", "Développer la résilience face au réchauffement climatique."],
    ["Renforcer la collaboration Ã‰tat-jeunesse pour la paix sociale.", "Renforcer la collaboration État-jeunesse pour la paix sociale."],
    ["Citoyennete et developpement local", "Citoyenneté et développement local"],
    ["Sante et bien-etre", "Santé et bien-être"],
    ["Climat et energies renouvelables", "Climat et énergies renouvelables"],
    ["Jeunes engages CZI", "Jeunes engagés CZI"],
    ["Ã‰quipe locale CZI", "Équipe locale CZI"],
    ["Collectif Zero Indigent", "Collectif Zéro Indigent"],
    ["autour d une ambition claire:", "autour d'une ambition claire :"],
    ["transformer l engagement citoyen en impact concret pour les communautes.", "transformer l'engagement citoyen en impact concret pour les communautés."],
    ["Acceder a la plateforme", "Accéder à la plateforme"],
    ["A propos du CZI", "À propos du CZI"],
    ["Une jeunesse qui agit pour des communautes plus resilientes.", "Une jeunesse qui agit pour des communautés plus résilientes."],
    ["Le Collectif Zero Indigent est un reseau de jeunes, d associations et d entrepreneurs mobilises pour", "Le Collectif Zéro Indigent est un réseau de jeunes, d'associations et d'entrepreneurs mobilisés pour"],
    ["accelerer l atteinte des ODD, avec un focus prioritaire sur la lutte contre la pauvrete et", "accélérer l'atteinte des ODD, avec un focus prioritaire sur la lutte contre la pauvreté et"],
    ["l autonomisation durable.", "l'autonomisation durable."],
    ["Â« Faire de chaque jeune un acteur engage dans l atteinte des ODD. Â»", "« Faire de chaque jeune un acteur engagé dans l'atteinte des ODD. »"],
    ["Voir la presentation complete", "Voir la présentation complète"],
    ["Contribuer, grace a la synergie d actions des jeunes, a l atteinte des ODD.", "Contribuer, grâce à la synergie d'actions des jeunes, à l'atteinte des ODD."],
    ["Outiller, orienter et accompagner la jeunesse vers l insertion et l impact local.", "Outiller, orienter et accompagner la jeunesse vers l'insertion et l'impact local."],
    ["PrioritÃ©s CZI", "Priorités CZI"],
    ["Les 07 axes strategiques", "Les 07 axes stratégiques"],
    ["Creer un compte", "Créer un compte"]
  ],
  'app/a-propos/page.tsx': [
    ["employabilite", "employabilité"],
    ["creation de richesses", "création de richesses"],
    ["Citoyennete et developpement local", "Citoyenneté et développement local"],
    ["Sante et bien-etre", "Santé et bien-être"],
    ["Rechauffement climatique et energies renouvelables", "Réchauffement climatique et énergies renouvelables"],
    ["A propos du CZI", "À propos du CZI"],
    ["Collectif Zero Indigent (CZI)", "Collectif Zéro Indigent (CZI)"],
    ["cadre d engagement citoyen et entrepreneurial fonde par des", "cadre d'engagement citoyen et entrepreneurial fondé par des"],
    ["transformer les communautes par l innovation sociale,", "transformer les communautés par l'innovation sociale,"],
    ["economique et environnementale.", "économique et environnementale."],
    ["Retour accueil", "Retour à l'accueil"],
    ["grace a la synergie d actions", "grâce à la synergie d'actions"],
    ["a l atteinte des Objectifs de Developpement Durable", "à l'atteinte des Objectifs de Développement Durable"],
    ["accelerer", "accélérer"],
    ["Domaines d intervention", "Domaines d'intervention"],
    ["Activites CZI", "Activités CZI"]
  ],
  'app/app/a-propos/page.tsx': [
    ["Identite", "Identité"],
    ["reseau de jeunes engages", "réseau de jeunes engagés"],
    ["organise autour de la cooperation", "organisé autour de la coopération"],
    ["Priorite", "Priorité"],
    ["priorite strategique est l ODD 1", "priorité stratégique est l'ODD 1"],
    ["actions concretes", "actions concrètes"],
    ["Citoyennete et developpement local", "Citoyenneté et développement local"],
    ["Sante et bien-etre", "Santé et bien-être"],
    ["Transition Ã©cole-emploi", "Transition école-emploi"],
    ["Resilience climatique", "Résilience climatique"],
    ["Axes strategiques", "Axes stratégiques"],
    ["A propos", "À propos"],
    ["Collectif Zero Indigent (CZI)", "Collectif Zéro Indigent (CZI)"],
    ["reseau de jeunes qui mobilise la synergie d actions pour accelerer l atteinte", "réseau de jeunes qui mobilise la synergie d'actions pour accélérer l'atteinte"],
    ["Objectifs de Developpement Durable", "Objectifs de Développement Durable"],
    ["met l accent sur", "met l'accent sur"],
    ["Domaines d action", "Domaines d'action"]
  ],
  'app/(auth)/signup/page.tsx': [
    ["Supabase non configure. Ajoutez les variables d'environnement.", "Supabase non configuré. Ajoutez les variables d'environnement."],
    ["Compte crÃ©Ã©. VÃ©rifiez votre email pour confirmer l'inscription, puis connectez-vous.", "Compte créé. Vérifiez votre email pour confirmer l'inscription, puis connectez-vous."],
    ["Creez un compte pour demarrer votre onboarding.", "Créez un compte pour démarrer votre onboarding."],
    ['<option value="personal">Personal</option>', '<option value="personal">Individuel</option>'],
    ['<option value="enterprise">Enterprise</option>', '<option value="enterprise">Entreprise</option>'],
    ["Creation...", "Création..."],
    ["Creer mon compte", "Créer mon compte"],
    ["Deja inscrit?", "Déjà inscrit ?"]
  ],
  'app/(auth)/forgot-password/page.tsx': [
    ["Supabase non configure. Ajoutez les variables d'environnement.", "Supabase non configuré. Ajoutez les variables d'environnement."],
    ["Un email de reinitialisation a ete envoye. Ouvrez le lien pour definir un nouveau mot de passe.", "Un email de réinitialisation a été envoyé. Ouvrez le lien pour définir un nouveau mot de passe."],
    ["Mot de passe oublie", "Mot de passe oublié"],
    ["Saisissez votre email pour recevoir un lien de reinitialisation.", "Saisissez votre email pour recevoir un lien de réinitialisation."],
    ["Retour a la", "Retour à la"]
  ],
  'app/(auth)/reset-password/page.tsx': [
    ["Supabase non configure. Ajoutez les variables d'environnement.", "Supabase non configuré. Ajoutez les variables d'environnement."],
    ["Session de reinitialisation invalide ou expiree.", "Session de réinitialisation invalide ou expirée."],
    ["Le mot de passe doit contenir au moins 8 caractÃ¨res.", "Le mot de passe doit contenir au moins 8 caractères."],
    ["Mot de passe mis a jour. Redirection vers la connexion...", "Mot de passe mis à jour. Redirection vers la connexion..."],
    ["Reinitialiser le mot de passe", "Réinitialiser le mot de passe"],
    ["Definissez un nouveau mot de passe pour votre compte.", "Définissez un nouveau mot de passe pour votre compte."],
    ["Verification de la session...", "Vérification de la session..."],
    ["Lien invalide ou expire. Redemandez un nouvel email de reinitialisation.", "Lien invalide ou expiré. Redemandez un nouvel email de réinitialisation."],
    ["Mise a jour...", "Mise à jour..."],
    ["Mettre a jour", "Mettre à jour"],
    ["Retour a la", "Retour à la"]
  ],
  'app/onboarding/actions.ts': [
    ["Appliquez le script SQL `sql/2026-02-21_fix_member_profile_rls.sql` dans Supabase, puis reessayez.", "Appliquez le script SQL `sql/2026-02-21_fix_member_profile_rls.sql` dans Supabase, puis réessayez."],
    ["Supabase non configure. Ajoutez NEXT_PUBLIC_SUPABASE_URL et NEXT_PUBLIC_SUPABASE_ANON_KEY.", "Supabase non configuré. Ajoutez NEXT_PUBLIC_SUPABASE_URL et NEXT_PUBLIC_SUPABASE_ANON_KEY."],
    ["Etape 1 incomplete: renseignez prenom, nom et telephone.", "Étape 1 incomplète : renseignez prénom, nom et téléphone."],
    ["Etape 2 incomplete: selectionnez region, prefecture et commune.", "Étape 2 incomplète : sélectionnez région, préfecture et commune."],
    ["Etape 3 incomplete: selectionnez le type d'inscription.", "Étape 3 incomplète : sélectionnez le type d'inscription."],
    ["Date de naissance ou tranche d'age obligatoire.", "Date de naissance ou tranche d'âge obligatoire."],
    ["Niveau d'education et statut professionnel obligatoires.", "Niveau d'éducation et statut professionnel obligatoires."],
    ["Objectif a 3-6 mois obligatoire.", "Objectif à 3-6 mois obligatoire."],
    ["Preference de contact invalide.", "Préférence de contact invalide."],
    ["Veuillez saisir au moins un centre d'intÃ©rÃªt.", "Veuillez saisir au moins un centre d'intérêt."],
    ["Selectionnez entre 1 et 3 ODD prioritaires.", "Sélectionnez entre 1 et 3 ODD prioritaires."],
    ["Veuillez selectionner au moins un type de support.", "Veuillez sélectionner au moins un type de support."],
    ["Pour le profil engage, domaines, frequence et action recente sont obligatoires.", "Pour le profil engagé, domaines, fréquence et action récente sont obligatoires."],
    ["Pour le profil responsable organisation, rÃ´le et nom dÃ©clarÃ© sont obligatoires.", "Pour le profil responsable d'organisation, rôle et nom déclaré sont obligatoires."]
  ],
  'app/onboarding/onboarding-form.tsx': [
    ['import type { CommuneOption, PrÃ©fectureOption, RÃ©gionOption } from "@/lib/backend/api";', 'import type { CommuneOption, PrefectureOption, RegionOption } from "@/lib/backend/api";'],
    ["Sante communautaire", "Santé communautaire"],
    ["Reseautage", "Réseautage"],
    ["Visibilite", "Visibilité"],
    ["IdentitÃ© et contact", "Identité et contact"],
    ["Competences et objectifs", "Compétences et objectifs"],
    ["setRÃ©gionId", "setRegionId"],
    ["setPrÃ©fectureId", "setPrefectureId"],
    ["setRÃ©gionsState", "setRegionsState"],
    ["setPrÃ©fecturesState", "setPrefecturesState"],
    ["RÃ©gionOption", "RegionOption"],
    ["PrÃ©fectureOption", "PrefectureOption"],
    ["nextRÃ©gions", "nextRegions"],
    ["nextPrÃ©fectures", "nextPrefectures"],
    ["filteredPrÃ©fectures", "filteredPrefectures"],
    ["prefectureIdsInRÃ©gion", "prefectureIdsInRegion"],
    ["Votre profil est deja complete. Ouvrez directement le dashboard.", "Votre profil est déjà complété. Ouvrez directement le tableau de bord."],
    ["Configuration territoriale incomplete (region/prefecture/commune). Ajoutez ces donnees dans Supabase avant de terminer l'onboarding.", "Configuration territoriale incomplète (région/préfecture/commune). Ajoutez ces données dans Supabase avant de terminer l'onboarding."],
    ["Impossible de charger region/prefecture/commune pour le moment.", "Impossible de charger région/préfecture/commune pour le moment."],
    ["Etape 1: date de naissance ou tranche d'age obligatoire.", "Étape 1 : date de naissance ou tranche d'âge obligatoire."],
    ["Etape 1: niveau d'education et statut professionnel obligatoires.", "Étape 1 : niveau d'éducation et statut professionnel obligatoires."],
    ["Etape 3: profil engage incomplet (domaines/frequence/action).", "Étape 3 : profil engagé incomplet (domaines/fréquence/action)."],
    ["TÃ©lÃ©phone", "Téléphone"],
    ["Tranche d&apos;age", "Tranche d&apos;âge"],
    ["Niveau d&apos;education", "Niveau d&apos;éducation"],
    ["Etudiant", "Étudiant"],
    ["SalariÃ©", "Salarié"],
    ["IndÃ©pendant", "Indépendant"],
    ["Ex: ChargÃ© de projet, DÃ©veloppeur, Artisane", "Ex : Chargé de projet, Développeur, Artisane"],
    ["RÃ©gion", "Région"],
    ["SÃ©lectionner une region", "Sélectionner une région"],
    ["PrÃ©fecture", "Préfecture"],
    ["SÃ©lectionner une prefecture", "Sélectionner une préfecture"],
    ["SÃ©lectionner une commune", "Sélectionner une commune"],
    ["SÃ©lectionner d'abord une region", "Sélectionner d'abord une région"],
    ["Quartier/LocalitÃ©", "Quartier/Localité"],
    ["Disponible pour activitÃ©s hors commune", "Disponible pour activités hors commune"],
    ["Zones de mobilitÃ©", "Zones de mobilité"],
    ['<option value="personal">Personal</option>', '<option value="personal">Individuel</option>'],
    ['<option value="enterprise">Enterprise</option>', '<option value="enterprise">Entreprise</option>'],
    ["Jeune engagÃ©", "Jeune engagé"],
    ["FrÃ©quence d&apos;engagement", "Fréquence d&apos;engagement"],
    ["Action rÃ©cente", "Action récente"],
    ["Decrivez une action recente", "Décrivez une action récente"],
    ["IdÃ©e", "Idée"],
    ["RÃ´le dans l&apos;organisation", "Rôle dans l&apos;organisation"],
    ["Ex: President, Coordinatrice", "Ex : Président, Coordinatrice"],
    ["Nom organisation dÃ©clarÃ©e", "Nom de l'organisation déclarée"],
    ["D. Competences, ODD et objectifs", "D. Compétences, ODD et objectifs"],
    ["Competences (separees par virgules)", "Compétences (séparées par des virgules)"],
    ["Centres d&apos;intÃ©rÃªt", "Centres d&apos;intérêt"],
    ["Quel est votre objectif principal sur 3 Ã  6 mois ?", "Quel est votre objectif principal sur 3 à 6 mois ?"],
    ["DisponibilitÃ©", "Disponibilité"],
    ["PrÃ©fÃ©rence de contact", "Préférence de contact"],
    ["J&apos;accepte l&apos;usage IA agrÃ©gÃ©/anonyme (optionnel)", "J&apos;accepte l&apos;usage IA agrégé/anonyme (optionnel)"],
    ["VÃ©rifiez vos informations, puis cliquez sur <strong>Terminer l&apos;onboarding</strong>.", "Vérifiez vos informations, puis cliquez sur <strong>Terminer l&apos;onboarding</strong>."],
    ["Vos donnÃ©es sont sauvegardÃ©es localement Ã  chaque Ã©tape tant que la soumission finale", "Vos données sont sauvegardées localement à chaque étape tant que la soumission finale"],
    ["n&apos;est pas envoyÃ©e.", "n&apos;est pas envoyée."],
    ["AprÃ¨s validation de votre fiche, vous retrouverez la nouvelle page", "Après validation de votre fiche, vous retrouverez la nouvelle page"],
    ["demander votre carte CZI a", "demander votre carte CZI à"],
    ["prÃ©ciser la remise.", "préciser la remise."],
    ["Chargement des donnÃ©es...", "Chargement des données..."],
    ["Wizard onboarding: etape", "Assistant d'onboarding : étape"],
    ["PrÃ©cÃ©dent", "Précédent"],
    ["CrÃ©ation en cours...", "Création en cours..."]
  ],
  'app/app/campagnes-email/actions.ts': [
    ["Supabase non configure.", "Supabase non configuré."],
    ["SÃ©lectionnez une rÃ©gion cible.", "Sélectionnez une région cible."],
    ["SÃ©lectionnez une prÃ©fecture cible.", "Sélectionnez une préfecture cible."],
    ["SÃ©lectionnez une commune cible.", "Sélectionnez une commune cible."],
    ["Impossible de creer la campagne email.", "Impossible de créer la campagne email."],
    ["Campagne creee en brouillon.", "Campagne créée en brouillon."],
    ["Campagne envoyee.", "Campagne envoyée."]
  ],
  'app/app/campagnes-email/campagnes-email-client.tsx': [
    ["RÃ©gion :", "Région :"],
    ["PrÃ©fecture :", "Préfecture :"],
    ["Commune:", "Commune :"],
    ["Envoi ciblÃ© Ã  toutes les rÃ©gions, ou par rÃ©gion/prÃ©fecture/commune.", "Envoi ciblé à toutes les régions, ou par région/préfecture/commune."],
    ["AccÃ¨s rÃ©servÃ© Ã  admin/ca/cn/pf/Ã©quipe communication. RÃ´le dÃ©tectÃ© :", "Accès réservé à admin/ca/cn/pf/équipe communication. Rôle détecté :"],
    ["RÃ´le actif :", "Rôle actif :"],
    ["RÃ©initialiser", "Réinitialiser"],
    ["CrÃ©er une campagne pour communiquer rapidement avec le rÃ©seau.", "Créer une campagne pour communiquer rapidement avec le réseau."],
    ["CrÃ©Ã©e le", "Créée le"],
    [">{item.status}<", ">{formatCampaignStatusLabel(item.status)}<"],
    ["envoyÃ©s", "envoyés"],
    ["Par rÃ©gion", "Par région"],
    ["Par prÃ©fecture", "Par préfecture"],
    [">Region<", ">Région<"],
    [">Prefecture<", ">Préfecture<"],
    ["SÃ©lectionner une rÃ©gion", "Sélectionner une région"],
    ["SÃ©lectionner une prÃ©fecture", "Sélectionner une préfecture"],
    ["SÃ©lectionner une commune", "Sélectionner une commune"],
    ["Creation...", "Création..."],
    ["CrÃ©er la campagne", "Créer la campagne"]
  ],
  'app/app/communiques/actions.ts': [
    ["Slectionnez une rgion.", "Sélectionnez une région."],
    ["Slectionnez une prfecture.", "Sélectionnez une préfecture."],
    ["Slectionnez une commune.", "Sélectionnez une commune."]
  ],
  'app/app/communiques/communiques-client.tsx': [
    ["Region:", "Région :"],
    ["PrÃ©fecture :", "Préfecture :"],
    ["Commune:", "Commune :"],
    [">Communiques<", ">Communiqués<"],
    ["Publication d&apos;annonces ciblees: national, region, prefecture ou commune.", "Publication d&apos;annonces ciblées : nationale, région, préfecture ou commune."],
    ["Nouveau communiquÃ©", "Nouveau communiqué"],
    ["Ã‰criture rÃ©servÃ©e Ã  l&apos;Ã©quipe communication, CA, CN, PF ou admin. RÃ´le dÃ©tectÃ© :", "Écriture réservée à l&apos;équipe communication, CA, CN, PF ou admin. Rôle détecté :"],
    ["RÃ©initialiser", "Réinitialiser"],
    ["Aucun communiquÃ© pour le moment", "Aucun communiqué pour le moment"],
    ["CrÃ©ez votre premier communiquÃ© pour informer les membres.", "Créez votre premier communiqué pour informer les membres."],
    ["publie", "publié"],
    ["CrÃ©Ã© le", "Créé le"],
    ["Titre du communiquÃ©", "Titre du communiqué"],
    ["Ã‰crivez votre annonce...", "Écrivez votre annonce..."],
    ["PortÃ©e", "Portée"],
    ["Par rÃ©gion", "Par région"],
    ["Par prÃ©fecture", "Par préfecture"],
    [">Region<", ">Région<"],
    [">Prefecture<", ">Préfecture<"],
    ["SÃ©lectionner une rÃ©gion", "Sélectionner une région"],
    ["SÃ©lectionner une prÃ©fecture", "Sélectionner une préfecture"],
    ["SÃ©lectionner une commune", "Sélectionner une commune"],
    ["Publier le communiquÃ©", "Publier le communiqué"],
    ["Modifier le communiquÃ©", "Modifier le communiqué"],
    ["Mise a jour...", "Mise à jour..."]
  ],
  'app/app/membres/[id]/actions.ts': [
    ["Impossible de mettre Ã  jour ce membre.", "Impossible de mettre à jour ce membre."],
    ["Impossible de mettre a jour le role.", "Impossible de mettre à jour le rôle."],
    ["Tous les champs obligatoires doivent etre renseignes.", "Tous les champs obligatoires doivent être renseignés."],
    ["Status invalide.", "Statut invalide."],
    ["SÃ©lectionnez une organisation existante ou renseignez un nouveau nom d'organisation.", "Sélectionnez une organisation existante ou renseignez un nouveau nom d'organisation."],
    ["Membre mis a jour.", "Membre mis à jour."],
    ["Role invalide.", "Rôle invalide."],
    ["Seuls les rÃ´les admin/ca peuvent modifier un rÃ´le.", "Seuls les rôles admin/ca peuvent modifier un rôle."],
    ["Le rÃ´le CA peut attribuer uniquement membre/pf/cn.", "Le rôle CA peut attribuer uniquement membre/pf/cn."],
    ["Le compte propriÃ©taire", "Le compte propriétaire"],
    ["doit conserver le rÃ´le admin.", "doit conserver le rôle admin."],
    ["RÃ´le non modifiÃ©. VÃ©rifiez les politiques `profile`, puis rÃ©appliquez `sql/2026-02-22_profile_role_governance_access.sql`.", "Rôle non modifié. Vérifiez les politiques `profile`, puis réappliquez `sql/2026-02-22_profile_role_governance_access.sql`."],
    ["Role mis a jour:", "Rôle mis à jour :"],
    ["Decision de validation invalide.", "Décision de validation invalide."],
    ["La cellule secondaire doit etre differente de la cellule primaire.", "La cellule secondaire doit être différente de la cellule primaire."]
  ],
  'app/app/membres/[id]/page.tsx': [
    ["Ajoutez les variables d&apos;environnement pour charger le detail membre.", "Ajoutez les variables d&apos;environnement pour charger le détail membre."],
    ["Ce membre n&apos;existe pas ou n&apos;est pas visible avec votre role actuel.", "Ce membre n&apos;existe pas ou n&apos;est pas visible avec votre rôle actuel."],
    ["Retour a la liste membres", "Retour à la liste des membres"],
    ["Role actif detecte:", "Rôle actif détecté :"],
    ["Ce profil est visible pour contact reseau. Les modifications sont reservees aux roles", "Ce profil est visible pour contact réseau. Les modifications sont réservées aux rôles"],
    ["Edition membre", "Édition membre"],
    ["Les modifications sont soumises a RLS. Un compte standard ne peut editer que ses", "Les modifications sont soumises à RLS. Un compte standard ne peut éditer que ses"],
    ["Validation membre", "Validation du membre"],
    ["Decision enregistree:", "Décision enregistrée :"],
    ["Ce role ne peut pas executer la validation membre.", "Ce rôle ne peut pas exécuter la validation du membre."],
    ["RÃ´le de gouvernance", "Rôle de gouvernance"],
    ["Admin peut nommer un autre admin et lui retirer ce role. CA peut attribuer", "Un admin peut nommer un autre admin et lui retirer ce rôle. Le CA peut attribuer"],
    ["uniquement membre/pf/cn. Le compte propriÃ©taire technique reste verrouillÃ© en admin.", "uniquement membre/pf/cn. Le compte propriétaire technique reste verrouillé en admin."]
  ],
  'app/app/support/page.tsx': [
    ["Assistant IA informatif uniquement: ne remplace pas un avis juridique, medical ou financier professionnel.", "Assistant IA à titre informatif uniquement : il ne remplace pas un avis juridique, médical ou financier professionnel."],
    ["Erreur chargement support IA.", "Erreur de chargement du support IA."]
  ],
  'lib/supabase/organisation.ts': [
    ["Aucune table organisations detectee. Donnees derivees depuis public.member.", "Aucune table organisations détectée. Données dérivées depuis public.member."],
    ["Table organisations dÃ©tectÃ©e mais schÃ©ma incompatible avec l'insertion MVP. ", "Table organisations détectée mais schéma incompatible avec l'insertion MVP. "],
    ["Impossible de creer l'organisation.", "Impossible de créer l'organisation."],
    ["Aucune table organisation/organization detectee pour l'insertion.", "Aucune table organisation/organization détectée pour l'insertion."]
  ],
  'app/app/carte-membre/page.tsx': [
    ["Complter l&apos;onboarding", "Compléter l&apos;onboarding"],
    ["Cette demande n&apos;est plus modifiable depuis votre espace car elle est dj en", "Cette demande n&apos;est plus modifiable depuis votre espace car elle est déjà en"],
    ["traitement ou finalise.", "traitement ou finalisée."],
    ["Le paiement en ligne sera activé\n                    ds son ouverture.", "Le paiement en ligne sera activé dès son ouverture."],
    ["Complter", "Compléter"]
  ],
  'app/app/dons/dons-client.tsx': [
    ["conservez votre reference", "conservez votre référence"],
    ["Enregistrément...", "Enregistrement..."],
    ["Enregistrér le don", "Enregistrer le don"],
    ["Payér maintenant", "Payer maintenant"]
  ],
  'app/(auth)/login/page.tsx': [
    ["Mot de passe oublié ", "Mot de passe oublié"],
    ["Pas encore de compte ", "Pas encore de compte ? "]
  ]
};

for (const [file, replacements] of Object.entries(replacementsByFile)) {
  applyReplacements(file, replacements);
}
